snowflake_dev:
  target: dbt_dev
  outputs:
    dbt_dev:
      type: snowflake
      account: CR71697.west-europe.azure
      role: DBT_DEV
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      threads: 4
      database: PROD
      schema: PUBLIC